### ISSUE TITLE
Send Weekly Cohort Emails

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFestival/open-leaders-planning#32]
## Overview
Each week we send out emails to the Project and Culture tracks. They detail any announcments from the previous week, the agenda and overview for the current week's call (including information on notes and assignments) as well as explaining what is due to happen in the following week.

## Templates
The templates are stored in individual GDocs for each track:

- [Project Track](https://docs.google.com/document/d/1yI2fNWcbsH7TwxI99tOHasvzFC50bPoFuep927Sc5GQ)
- [Culture Track](https://docs.google.com/document/d/1P8JhHx2Dzh-4-zeHHoaPZDPzn5bOKz8OYInYQKWnbUQ)

## Tasks
We need to send out emails for the following weeks:
- [x] Week 1 (Not Tracked On GH)
- [x] Week 2 (Tracked in #25)
- [x] Week 3 (Tracked in #27)
- [x] Week 4 (Tracked in #31)
- [x] Week 5
- [x] Week 6
- [x] Week 7
- [x] Week 8
- [x] Week 9
- [x] Week 10
- [x] Week 11
- [x] Week 12
- [x] Week 13
- [ ] Week 14

@acabunoc will check Project Track emails and @chadsansing the Culture Track emails weekly for any required changes and @marcwalsh will send them to each cohort.

**Comment by marcwalsh** [comment]
Let me know when the emails for Week 5 are good to send by checking the box below!

- [x] Week 5 Project Track (@acabunoc)
- [x] Week 5 Culture Track (@chadsansing)

Thanks!

**Comment by abbycabs** [comment]
I've updated the doc with emails for weeks 5, 6, 7 & 8!

**Comment by marcwalsh** [comment]
Once you've reviewed emails for Week 6 please let me know they're good to send by ticking the box below, and uncheck if changes need to be made! :)

- [x] Week 6 Project Track (@acabunoc)
- [x] Week 6 Culture Track (@chadsansing)

Thanks!

**Comment by marcwalsh** [comment]
Once you've reviewed emails for Week 7 please let me know they're good to send by ticking the box below, and uncheck if changes need to be made! :)

- [x] Week 7 Project Track (@acabunoc)
- [x] Week 7 Culture Track (@chadsansing)

Thanks!

**Comment by marcwalsh** [comment]
Once you've reviewed emails for Week 8 please let me know they're good to send by ticking the box below, and uncheck if changes need to be made! :)

- [x] Week 8 Project Track (@acabunoc)
- [x] Week 8 Culture Track (@chadsansing)

Thanks!

**Comment by marcwalsh** [comment]
Once you've reviewed emails for Week 9 please let me know they're good to send by ticking the box below, and uncheck if changes need to be made! :)

- [x] Week 9 Project Track (@acabunoc)
- [x] Week 9 Culture Track (@chadsansing)

Thanks!

**Comment by marcwalsh** [comment]
@acabunoc - I updated the Week 9 email with the OL7 link :)

**Comment by marcwalsh** [comment]
Once you've reviewed emails for Week 10 please let me know they're good to send by ticking the box below, and uncheck if changes need to be made! :)

- [x] Week 10 Project Track (@acabunoc)
- [x] Week 10 Culture Track (@chadsansing)

Thanks!

**Comment by marcwalsh** [comment]
Once you've reviewed emails for Week 11 please let me know  they're good to send by ticking the box below, and uncheck if changes need to be made! :)

- [x] Week 11 Project Track (@acabunoc)
- [x] Week 11 Culture Track (@chadsansing)

Thanks!

**Comment by marcwalsh** [comment]
Once you've reviewed emails for Week 12 please let me know they're good to send by ticking the box below, and uncheck if changes need to be made! :)

- [x] Week 12 Project Track (@acabunoc)
- [x] Week 12 Culture Track (@chadsansing)

Thanks!

**Comment by marcwalsh** [comment]
For the last time this cohort... Once you've reviewed emails for Week 14 please let me know they're good to send by ticking the box below, and uncheck if changes need to be made! :)

- [x] Week 14 Project Track (@acabunoc)
- [ ] Week 14 Culture Track (@chadsansing)

Thanks!
